import { quarterProjectListType } from "../types";

const quarterProjectList: quarterProjectListType = {
  data: [
    {
      id: "202203",
      quarter: "2022 q3",
      projectList: [
        {
          id: "2022030101-dev",
          name: "비즈하우스 홈 - 리뷰 파트 리뉴얼 (데스크탑)",
          date: "2022년 09월",
          skill: [
            "React",
            "React-Query",
            "HTML",
            "CSS",
            "JSON",
            "TypeScript",
          ],
          description:
            "데스크탑은 무한 자동 캐러셀(마우스 오버 시 멈췄다가 마우스가 멀어지면 다시 반복), 모바일은 스와이프 캐러셀을 구현하였습니다. 새로운 api가 필요해서 요청 api 문서를 작성하여 백엔드 개발자 분께 전달하며 협업하였고, 디자이너 분과는 피그마를 통해 소통하였습니다. 또한 QA & 프로젝트 매니저 분과 소통하며 깊은 완성도로 마무리 했습니다.",
          video: "/video/2022030101.mp4",
        },
        {
          id: "2022030102-dev",
          name: "비즈하우스 홈 - 리뷰 파트 리뉴얼 (모바일)",
          date: "2022년 09월",
          skill: [
            "React",
            "React-Query",
            "HTML",
            "CSS",
            "JSON",
            "TypeScript",
          ],
          description:
            "데스크탑은 무한 자동 캐러셀(마우스 오버 시 멈췄다가 마우스가 멀어지면 다시 반복), 모바일은 스와이프 캐러셀을 구현하였습니다. 새로운 api가 필요해서 요청 api 문서를 작성하여 백엔드 개발자 분께 전달하며 협업하였고, 디자이너 분과는 피그마를 통해 소통하였습니다. 또한 QA & 프로젝트 매니저 분과 소통하며 깊은 완성도로 마무리 했습니다.",
          video: "/video/2022030102.mov",
        },
        {
          id: "20220302",
          name: "그 외 프로젝트",
          date: "2022년 07월 ~ 09월",
          skill: [
            "React",
            "React-Query",
            "HTML",
            "CSS",
            "JSON",
            "TypeScript",
            "DayJS",
            "Emotion",
            "Sass",
          ],
          description:
            "인턴 기간 2개월 포함 3개월 동안 총 40개의 이슈를 진행 및 배포하며 비즈하우스 옵션페이지 및 템플릿페이지 유지보수 & 일부 리뉴얼 / 미리캔버스 에디터 - 배송 파트 리뉴얼 프론트엔드 파트를 담당했습니다. 또한 레거시를 대상으로 eslint 무효화 주석을 제거 후 리팩토링하는 이슈도 담당했고, 온보딩 스몰 이슈들을 진행하며 회사 코드와 흐름에 대해 익혔습니다.",
        },
      ],
    },
    {
      id: "202204",
      quarter: "2022 q4",
      projectList: [
        {
          id: "20220401",
          name: "비즈하우스 모바일 - 헤더 리뉴얼",
          date: "2022년 10월",
          skill: [
            "React",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
          ],
          description:
            "해당 프로젝트로 비즈하우스의 모든 모바일 헤더가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. feature 패키지를 새로 만들어서 총 8개의 헤더를 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/20220401.mov",
        },
        {
          id: "20220402",
          name: "비즈하우스 모바일 - 바텀 네비게이션 리뉴얼",
          date: "2022년 10월",
          skill: [
            "React",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
          ],
          description:
            "해당 프로젝트로 비즈하우스 - 모바일 바텀네비게이션이 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 또한 아이폰 하단바에 대응하는 CSS를 추가하여 사용자 만족도를 높였습니다. feature 패키지를 새로 만들어서 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/20220402.mov",
        },
        {
          id: "20220403",
          name: "비즈하우스 모바일 - 카테고리 페이지 리뉴얼",
          date: "2022년 11월",
          skill: [
            "React",
            "React-Query",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
            "JSON",
          ],
          description:
            "해당 프로젝트로 비즈하우스 - 모바일 카테고리가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 스토리지를 사용하여 카테고리별 최근 본 내역이 있는 경우엔 최근 본 상품/의뢰/디자인을 보여주도록 하였고, 최근 본 내역이 없는 경우엔 각 카테고리 기능을 보여주도록 구현하였습니다. 바텀 네비게이션이 리뉴얼 되며 새롭게 만들어진 feature 패키지 안에서 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/20220403.mov",
        },
        {
          id: "20220404",
          name: "비즈하우스 고객업종모달 리뉴얼",
          date: "2022년 12월",
          skill: [
            "React",
            "React-Query",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
          ],
          description:
            "해당 프로젝트로 비즈하우스 - 고객업종등록 모달이 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. Recoil을 사용하여 컴포넌트 간에 상태를 공유하도록 하였고, 등록 모달이 뜨는 페이지 플로우에 대한 정확한 정책이 없어서, 기획자 분과 협의하며 사용자 편의성을 생각하여 직접 의견을 내며 개발하였습니다. 또한 React-Query로 등록할 때 필요한 카테고리 데이터를 Get 가져왔고, 유저가 선택한 데이터를 Post 로 백엔드에 보내며 통신하였습니다. feature 패키지를 새로 만들어 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/20220404.mov",
        },
        {
          id: "20220405",
          name: "그 외 프로젝트",
          date: "2022년 10월 ~ 12월",
          skill: [
            "React",
            "React-Query",
            "HTML",
            "CSS",
            "JSON",
            "TypeScript",
            "DayJS",
            "Emotion",
            "Sass",
          ],
          description:
            "4분기 3개월 동안 총 35개의 이슈를 진행 및 배포하며 비즈하우스 나의 디자인 페이지 유지보수 & 일부 리뉴얼 프론트엔드 파트를 담당했습니다. 또한 신규 입사자 분들을 위해 작성되어 있던 기존 문서들이 비즈니스 용어가 많아 어렵다는 의견이 있어, 쉽게 풀어내어 새로 작성하였고. 동료 개발자 분들의 작업에 대한 코드 리뷰 등 기타 업무를 담당하였습니다.",
        },
      ],
    },
    {
      id: "202301",
      quarter: "2023 q1",
      projectList: [
        {
          id: "2023010101-dev",
          name: "비즈하우스 장바구니 페이지 - 추천상품 파트 (데스크탑)",
          date: "2023년 01월",
          skill: [
            "React",
            "HTML",
            "CSS",
            "TypeScript",
            "React-Query",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 > 장바구니 페이지에 추천상품이라는 파트가 새로 탄생되었습니다. 장바구니에 담긴 사용자의 상품에 따라 연관성 있는 상품을 추천하고, 사용자의 디자인 혹은 자사 미리캔버스 템플릿을 활용하여 목업뷰어를 보여줄 수 있도록 구현했습니다. 또한 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010101.mov",
        },
        {
          id: "2023010102-dev",
          name: "비즈하우스 장바구니 페이지 - 추천상품 파트 (모바일)",
          date: "2023년 01월",
          skill: [
            "React",
            "HTML",
            "CSS",
            "TypeScript",
            "React-Query",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 > 장바구니 페이지에 추천상품이라는 파트가 새로 탄생되었습니다. 장바구니에 담긴 사용자의 상품에 따라 연관성 있는 상품을 추천하고, 사용자의 디자인 혹은 자사 미리캔버스 템플릿을 활용하여 목업뷰어를 보여줄 수 있도록 구현했습니다. 또한 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010102.mov",
        },
        {
          id: "2023010201-dev",
          name: "비즈하우스 아이디/비밀번호 찾기 모달 - 유저 관련 플로우 전체 모달 (데스크탑)",
          date: "2023년 2월",
          skill: [
            "React",
            "Recoil",
            "React-Query",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 아이디/비밀번호 찾기 모달을 포함하여 유저 관련 플로우 전체 모달이 기존 JSP 코드에서 tsx 코드로 변경 및 UI & UX 리뉴얼 되었습니다. feature 패키지를 새로 만들어서 구현하였으며, 백엔드 개발자와 커뮤니케이션을 하며 api 설계에도 참여했습니다. 또한 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010201.mov",
        },
        {
          id: "2023010202-dev",
          name: "비즈하우스 아이디/비밀번호 찾기 모달 - 유저 관련 플로우 전체 모달 (모바일)",
          date: "2023년 2월",
          skill: [
            "React",
            "Recoil",
            "React-Query",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 아이디/비밀번호 찾기 모달을 포함하여 유저 관련 플로우 전체 모달이 기존 JSP 코드에서 tsx 코드로 변경 및 UI & UX 리뉴얼 되었습니다. feature 패키지를 새로 만들어서 구현하였으며, 백엔드 개발자와 커뮤니케이션을 하며 api 설계에도 참여했습니다. 또한 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010202.mov",
        },
        {
          id: "2023010301-dev",
          name: "비즈하우스 마이페이지 - 회원정보수정 페이지 리뉴얼 (데스크탑)",
          date: "2023년 3월",
          skill: [
            "React",
            "React-Query",
            "Recoil",
            "react-daum-postcode",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 회원정보수정 페이지가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 사용자에게 우편번호 서비스를 제공하기 위해 기본적으론 daum-postcode 를 사용하도록 했지만, 카카오 서비스가 안정적이지 않을 땐 행정안전부 서비스를 사용하도록 구현했습니다. page 패키지를 새로 만들어 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010301.mov",
        },
        {
          id: "2023010302-dev",
          name: "비즈하우스 마이페이지 - 회원정보수정 페이지 리뉴얼 (태블릿)",
          date: "2023년 3월",
          skill: [
            "React",
            "React-Query",
            "Recoil",
            "react-daum-postcode",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 회원정보수정 페이지가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 사용자에게 우편번호 서비스를 제공하기 위해 기본적으론 daum-postcode 를 사용하도록 했지만, 카카오 서비스가 안정적이지 않을 땐 행정안전부 서비스를 사용하도록 구현했습니다. page 패키지를 새로 만들어 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010302.mov",
        },
        {
          id: "2023010303-dev",
          name: "비즈하우스 마이페이지 - 회원정보수정 페이지 리뉴얼 (모바일)",
          date: "2023년 3월",
          skill: [
            "React",
            "React-Query",
            "Recoil",
            "react-daum-postcode",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 회원정보수정 페이지가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 사용자에게 우편번호 서비스를 제공하기 위해 기본적으론 daum-postcode 를 사용하도록 했지만, 카카오 서비스가 안정적이지 않을 땐 행정안전부 서비스를 사용하도록 구현했습니다. page 패키지를 새로 만들어 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010303.mov",
        },
        {
          id: "2023010401-dev",
          name: "비즈하우스 마이페이지 - 탈퇴 페이지 리뉴얼 (데스크탑)",
          date: "2023년 3월",
          skill: [
            "React",
            "React-Query",
            "Recoil",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 탈퇴 페이지가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 최대한 탈퇴를 하지 않도록 설득하나, 최대한 좋은 인상으로 남길 수 있도록 사용성에 신경 써서 구현했습니다. page 패키지를 새로 만들어 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010401.mov",
        },
        {
          id: "2023010402-dev",
          name: "비즈하우스 마이페이지 - 탈퇴 페이지 리뉴얼 (태블릿)",
          date: "2023년 3월",
          skill: [
            "React",
            "React-Query",
            "Recoil",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 탈퇴 페이지가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 최대한 탈퇴를 하지 않도록 설득하나, 최대한 좋은 인상으로 남길 수 있도록 사용성에 신경 써서 구현했습니다. page 패키지를 새로 만들어 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010402.mov",
        },
        {
          id: "2023010403-dev",
          name: "비즈하우스 마이페이지 - 탈퇴 페이지 리뉴얼 (모바일)",
          date: "2023년 3월",
          skill: [
            "React",
            "React-Query",
            "Recoil",
            "HTML",
            "CSS",
            "TypeScript",
            "JSP",
            "Emotion",
          ],
          description:
              "해당 프로젝트로 비즈하우스 - 탈퇴 페이지가 기존 JSP 코드에서 TSX 코드로 변경 및 UI & UX 리뉴얼 되었습니다. 최대한 탈퇴를 하지 않도록 설득하나, 최대한 좋은 인상으로 남길 수 있도록 사용성에 신경 써서 구현했습니다. page 패키지를 새로 만들어 구현하였으며, 추후 다른 개발자가 코드를 보기 쉽도록 개발자를 위한 dev 모드를 구현하고 설계 및 구조 ReadME를 작성하였습니다.",
          video: "/video/2023010403.mov",
        },
        {
          id: "20230105",
          name: "비즈글로벌 그리고 외 프로젝트",
          date: "2023년 3월",
          skill: [
            "React",
            "Recoil",
            "react-i18next",
            "React-Query",
            "TypeScript",
            "DayJS",
            "Emotion",
            "HTML",
            "CSS",
            "JSON",
            "JSP",
            "Sass",
          ],
          description:
              "1분기 3개월 동안 총 70개의 이슈를 진행 및 배포하며 일부 리뉴얼 프로젝트의 프론트엔드 개발을 담당했습니다. 그리고 3월 중후반부턴 비즈하우스 글로벌 스쿼드 (TF) 의 프론트엔드 담당으로 글로벌 프로젝트를 진행하고 있습니다. 뿐만 아니라 레거시 코드를 리팩토링하고, 보다 더 나은 개발 환경을 만들기 위해 린트와 같은 내부 개발 이슈들에도 적극 참여하였습니다. 그리고 동료 개발자 분들의 작업에 대한 코드 리뷰 등 기타 업무를 담당하였습니다.",
        },
      ],
    },
  ],
};

export default quarterProjectList;
